### PR TITLE
Explicit count modifiers

### PR DESCRIPTION
**Pull request by pchaigno**
The construction `{,2}` in regular expressions is only supported by Oniguruma (which is used by Sublime Text). This package is used to highlight Netlinx code on GitHub. However, GitHub is using a [PCRE-based engine](https://github.com/vmg/pcre) for regexes and thus, the following code gets incorrectly highlighted.

``` netlinx
dvDebug = '\00';
```

This pull request fixes that by using an explicit count modifier in the regex.

### CODE REVIEW

**Comment by amclain** [comment]
Thanks for the PR. Wouldn't it make more sense to remove `constant.character.escape.netlinx` all together since NetLinx doesn't support escaping strings?

This appears to be related to issue #5.

**Comment by pchaigno** [comment]
> Wouldn't it make more sense to remove constant.character.escape.netlinx all together since NetLinx doesn't support escaping strings?

I'm not familiar with NetLinx so I wouldn't know.

I'm curious though, how do you create a string with `let's encrypt` for instance in NetLinx?

**Comment by amclain** [comment]
> I'm not familiar with NetLinx so I wouldn't know.

I was under the impression that you were a NetLinx programmer who was trying to fix a bug that was impacting your workflow. I recommend reading the [NetLinx Language Reference Guide](http://www.amx.com//assets/manuals/NetLinx.LanguageReferenceGuide.pdf) and familiarizing yourself with the language before trying to modify the syntax highlighting. Ideally you should also purchase an [AMX master controller](http://www.amx.com/products/NX-1200.asp) to be able to execute NetLinx code.

> I'm curious though, how do you create a string with `let's encrypt` for instance in NetLinx?

NetLinx uses byte arrays, with single quotes designating the ASCII portions. The apostrophe in the string would be written as hex `$27` and concatenated. So in NetLinx your string would be defined like this:

``` netlinx
char myString[255];
myString = "'let', $27, 's encrypt'";
```

If you need more help with the language, AMX offers the [ACE-P programming certification course](http://www.amx.com/training/).

**Comment by pchaigno** [comment]
> NetLinx uses byte arrays, with single quotes designating the ASCII portions. The apostrophe in the string would be written as hex $27 and concatenated.

Thanks for the explanation! :sparkles: 
<br>

> I was under the impression that you were a NetLinx programmer who was trying to fix a bug that was impacting your workflow. I recommend reading the NetLinx Language Reference Guide and familiarizing yourself with the language before trying to modify the syntax highlighting. Ideally you should also purchase an AMX master controller to be able to execute NetLinx code.

I'm not interested in starting learning Netlinx (maybe on day though, who knows?).
I'm working on syntax highlighting and language detection on GitHub (see [github/linguist](https://github.com/github/linguist)) and I just wanted to fix this bug which was impacting more than 10 languages :/
<br>

Good luck fixing the bug ;)

**Comment by amclain** [comment]
Fixed in 2.1.1, changeset 6351ad866c4ec7d8043f155671c07981388a77bf.

**Pull request closed without merging**
